### PR TITLE
Update sgx_read_rand.cpp

### PR DESCRIPTION
**Pull request by jasl**
Just format code for better reading

### CODE REVIEW

**Comment by deeglaze** [comment]
Perhaps it's time this project got a .clang-format file and everything committed should be formatted with it.

**Comment by jasl** [comment]
agree, which style you prefer to?

**Comment by deeglaze** [comment]
I'm a Googler, so --style=google is good for me, but the Intel folks would need to agree on something. It looks like they prefer 4 space indentation instead of 2 space, for instance.

**Comment by jasl** [comment]
Lol my partner is a ex-Googler, I think formatting whole project would be a big change, let Intel guys decide it

**Comment by andyzyb** [comment]
Currently there is no plan to change the coding style which it was established a while ago.

**Pull request closed without merging**
