### PR TITLE
Support longjmp in exception handler

### PR DESCRIPTION
**Pull request by guzongmin**
If the customer exception handler use longjmp function, then the memory free would be skipped. So the malloc should be changed to alloca.

### CODE REVIEW

**Comment by lzha101** [comment]
Thanks for raising this issue and the fix. We also need to consider the case that the alloca() triggers a stack overrun exception, although the allocated buffer is just used to save the handler pointers.

**Comment by guzongmin** [comment]
> Thanks for raising this issue and the fix. We also need to consider the case that the alloca() triggers a stack overrun exception, although the allocated buffer is just used to save the handler pointers.

I think it is the second phrase execption handling, so even if the alloca function trigger #PF we still be able to handle it within another exception handling flow. 

[original exception handler (phrase 1)]
                    |
 [original exception handler (phrase 2)]  --------------> [#PF handler (phrase 1)] 
                                                                                                           |
 [original exception handler (phrase 2)] <----------------------- (ERESUME)
                    |
 [original exception handler (user phrase)]

**Comment by yuyuany** [comment]
I agree the exception can be handled, and SGX_ERROR_STACK_OVERRUN is returned if stack cannot grow. But we do not want exception happens in trts. It may make users confused.

**Comment by guzongmin** [comment]
> I agree the exception can be handled, and SGX_ERROR_STACK_OVERRUN is returned if stack cannot grow. But we do not want exception happens in trts. It may make users confused.

I think the fix is exactlly same as tRTS using a function with large local variables. BTW: If we do not use alloca, how can we fix this bug?

**Pull request merged**
