### PR TITLE
Make heap optionally executable

### PR DESCRIPTION
**Pull request by exFalso**
This PR adds a new xml option `ExecutableHeap` which causes the executable flag of the enclave heap to be set.

### CODE REVIEW

**Comment by andyzyb** [comment]
We will review this feature enhancement and provide the feedback. Thanks.

**Comment by lzha101** [comment]
@exFalso, what is your purpose to make heap executable? It is not a security feature.

**Comment by exFalso** [comment]
In our use case this is required for JIT compilation

**Comment by MWShan** [comment]
One concern about making the heap executable relates to a future instruction support, SGX2 instructions, which will allow pages to be added to the enclave after EINIT via the EAUG instruction.  This can be used to commit a small initial  heap and then later expand the heap (the process is detailed here: [http://caslab.csl.yale.edu/workshops/hasp2016/HASP16-17.pdf](url) )
)  Any dynamically allocated heap will be committed with RW attributes because the EAUG instruction adds pages with RW permission.  The enclave will be able to change pages from RW to RX with SGX2 instructions.

**Comment by exFalso** [comment]
We are trying to work with SGX1 currently, but it's great to hear about such upcoming features.

The flag is optional and is by default set to false, is this not sufficient?

**Comment by andyzyb** [comment]
PR will not be merged.  Using SGX2 for enhancement is recommended.

**Pull request closed without merging**
