### PR TITLE
Fix aesmd not starting if /dev is mounted as noexec

### PR DESCRIPTION
**Pull request by assafmo**
See https://lore.kernel.org/linux-sgx/4db41057-910c-b686-0428-474debe382c1@fortanix.com/

### CODE REVIEW

**Comment by assafmo** [comment]
So actually this didn't work for me. Instead of using `ExecStartPre` I had to create a startup script especially for remounting `/dev` as `exec`.

I don't know what you'd want to do with this PR or even if you want to support ubuntu != {16.04,18.04}.

Anyway I think the driver should make sure it is mounted as `exec`.

See https://github.com/enigmampc/EnigmaBlockchain/commit/866949a926edc9549c07f53545bcf13f97faef25?diff=split#diff-fc708eba6ce617e52f528df7404127e6R77-R90

**Comment by andyzyb** [comment]
I somewhat agree that it is better to leave this to driver.  In some cases there is no AESM installed on the system, then user application needs to handle this?

**Comment by assafmo** [comment]
I agree

**Comment by assafmo** [comment]
I don't this the user application needs to handle this, but the driver. I wouldn't want my apps to remount `/dev` on my system.  
Though if not AESM then I think the driver should handle this.

**Comment by haitaohuang** [comment]
This is discussed in LKML for upstreaming driver. It needs be a solution from driver

**Comment by kaimast** [comment]
Thanks for posting the fix @assafmo!

**Pull request closed without merging**
