### PR TITLE
Added a test suite for the constant-time instruction decoder (CTD).

### PR DESCRIPTION
**Pull request by scottconstable**
Signed-off by: Scott Constable <scott.d.constable@intel.com>

### CODE REVIEW

**Comment by xiaonan-INTC** [comment]
Dear Scott,

I saw there are **3 files** Makefile, ctd.c, ctd.h in sdk/trts/ folder:
- ctd_tests
- sdk/trts
    - Makefile
    - ctd.c
    - ctd.h
Does it mean the 3 files need to be added to SGX SDK source code: frameworks.security.confidential-computing.tee.sgx-linux/sdk/trts/, and compiled with SGX SDK source code to generate a installer and install, then ctd_tests can be run normally?

And I saw there are **4 tests** CTDTest, dudect, pithchfork, xed in ctd_tests/:
- ctd_tests
    - CTDTest
    - dudect
    - pitchfork
    - xed
- sdk/trts
Do they all need above 3 files Makefile, ctd.c, ctd.h in sdk/trts/ added to and compiled with SGX SDK source code?

**Comment by CXWorks** [comment]
Hi @xiaonan-INTC , thanks for reviewing the PR. 

> Does it mean the 3 files need to be added to SGX SDK source code: sdk/trts/, and compiled with SGX SDK source code to generate a installer and install, then ctd_tests can be run normally?

Yes, these 3 files are the source code of the constant time decoder.

> Do they all need above 3 files Makefile, ctd.c, ctd.h in sdk/trts/ added to and compiled with SGX SDK source code?

No, the constant time decoder can be built as a standalone program to test and doesn't need the SDK, these tests are for the standalone programs and some of them take days to finish.

For any questions or comments, please let me know.

**Comment by xiaonan-INTC** [comment]
> 

Thanks for the reply, @CXWorks 
I have merged ctd_tests

> Hi @xiaonan-INTC , thanks for reviewing the PR.
> 
> > Does it mean the 3 files need to be added to SGX SDK source code: sdk/trts/, and compiled with SGX SDK source code to generate a installer and install, then ctd_tests can be run normally?
> 
> Yes, these 3 files are the source code of the constant time decoder.
> 
> > Do they all need above 3 files Makefile, ctd.c, ctd.h in sdk/trts/ added to and compiled with SGX SDK source code?
> 
> No, the constant time decoder can be built as a standalone program to test and doesn't need the SDK, these tests are for the standalone programs and some of them take days to finish.
> 
> For any questions or comments, please let me know.

Thanks a lot, @CXWorks 
I have merged ctd_tests to our sgx-linux-qatests, and will use it to test CTD later, :)

**Comment by xiaonan-INTC** [comment]
Dear @CXWorks,

Sorry to trouble you, I met some issues when running ctd test suite:

1. In readme.md, "Instructions on how to convert source code to be compiled by clang-11" part,
There are 3 parts need to be changed:
>>What files need to be changed and how to change them? Could you help explain in detail?

2. In xed/readme.md, "2. Build CTD" part,
Run `./build_ctd.sh` at ctd folder
>>Where is the ctd folder?
And In xed/readme.md, "3. Set CTD env" part,
Set `$CTD_BIN` to the folder containing `ctd_test` as executable 
>>Where is the ctd_test folder?

3. For those files in sdk/, do I need to add/modify them in SGX SDK source code, then re-build a new SGX SDK and install, then CTD test could run normally?
-sdk
    -simulation/trtssim/linux/
        -Makefile
    -trts/
        -Makefile
        -ctd.h
        -ctd.c
        -linux/
            -trts_mitigation.S
        -trts_veh.cpp

**Comment by scottconstable** [comment]
Hi @xiaonan-INTC, I think that `$CTD_BIN` is supposed to point to the directory that contains the `ctd_test` binary. This binary is built by the `Makefile` in `sdk/trts`. So, I think that you need to do something like:
```
$ cd <path-to-linux-sgx>/sdk/trts
$ make ctd_test
$ export CTD_BIN=<path-to-linux-sgx>/sdk/trts
```
If this doesn't work, then @CXWorks may need to provide further guidance.

**Comment by xiaonan-INTC** [comment]
> Hi @xiaonan-INTC, I think that `$CTD_BIN` is supposed to point to the directory that contains the `ctd_test` binary. This binary is built by the `Makefile` in `sdk/trts`. So, I think that you need to do something like:
> 
> ```
> $ cd <path-to-linux-sgx>/sdk/trts
> $ make ctd_test
> $ export CTD_BIN=<path-to-linux-sgx>/sdk/trts
> ```
> 
> If this doesn't work, then @CXWorks may need to provide further guidance.

Thank for the guidance, Scott, :)

Dear @scottconstable @CXWorks, 

I am still a little confused about how to run CTD test:
1. what is the order of **modifying SGX SDK** and **convert source code to be compiled by clang-11**?
2. do we need to modify SGX SDK by applying files under sdk/, then build a new SGX SDK and install, so CTD test could run?
3. what does the source code in **convert source code to be compiled by clang-11** mean?
4. how to **convert source code to be compiled by clang-11**(in readme, there are 1, 2, 3 steps, but not clear of specific files and steps)?

**Comment by CXWorks** [comment]
> > Hi @xiaonan-INTC, I think that `$CTD_BIN` is supposed to point to the directory that contains the `ctd_test` binary. This binary is built by the `Makefile` in `sdk/trts`. So, I think that you need to do something like:
> > ```
> > $ cd <path-to-linux-sgx>/sdk/trts
> > $ make ctd_test
> > $ export CTD_BIN=<path-to-linux-sgx>/sdk/trts
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If this doesn't work, then @CXWorks may need to provide further guidance.
> 
> Thank for the guidance, Scott, :)
> 
> Dear @scottconstable @CXWorks,
> 
> I am still a little confused about how to run CTD test:
> 
> 1. what is the order of **modifying SGX SDK** and **convert source code to be compiled by clang-11**?

Could you please specifiy where to "modifying SGX SDK"? The "convert source code to be compiled by clang-11" only happens when you want to run the test suites for CTD.

> 2. do we need to modify SGX SDK by applying files under sdk/, then build a new SGX SDK and install, so CTD test could run?

I don't think so. Currently the CTD tests are separated as a standalone program, you can just "convert source code to be compiled by clang-11" and then launch the test without compiling SDK.

> 3. what does the source code in **convert source code to be compiled by clang-11** mean?

The source code is  "sdk/trts/ctd.c".

> 4. how to **convert source code to be compiled by clang-11**(in readme, there are 1, 2, 3 steps, but not clear of specific files and steps)?

File is "sdk/trts/ctd.c". 

1. Search for the 4 gcc built-ins and do the replacement.
2. Remove inline asm, convert them into "?:" operator
3. Remove  all the "cselect" operations in "register_select"

Then recompile CTD as a standalone program using clang-11, you can get the LLVM IR and binary for test suites.

**Comment by xiaonan-INTC** [comment]
> 

Dear @CXWorks 

Still met some errors, could you help check?
In readme.md
There are 3 parts need to be changed:
1. Built-in intrinsic. Previously we use gcc intrinsic in the source code since the sdk doesn't allow us to include avx2 header file. We need to add the header file and convert them back, otherwise these intrinsic are gcc only. The following intrinsic are I encountered(gcc_version -> clang_version):
                __builtin_ia32_pandn128 -> _mm_andnot_si128
                __builtin_ia32_andnotsi256 -> _mm256_andnot_si256
                __builtin_ia32_vinsertf128_si256 -> _mm256_insertf128_si256
                __builtin_ia32_si256_si -> _mm256_castsi128_si256
**[Xiaonan]**here are building errors as below:
ctd.c: In function ‘prefix_op1_lookup’:
ctd.c:961:32: warning: implicit declaration of function ‘_mm_andnot_si128’; did you mean ‘_mm_and_si128’? [-Wimplicit-function-declaration]
  961 |     __m128i op1_l4b = (__m128i)_mm_andnot_si128((__v2di)mask, (__v2di)query);
      |                                ^~~~~~~~~~~~~~~~
      |                                _mm_and_si128
ctd.c:961:5: error: can’t convert a value of type ‘int’ to vector type ‘__vector(2) long long int’ which has different size
  961 |     __m128i op1_l4b = (__m128i)_mm_andnot_si128((__v2di)mask, (__v2di)query);
      |     ^~~~~~~
ctd.c:966:9: error: can’t convert a value of type ‘int’ to vector type ‘__vector(2) long long int’ which has different size
  966 |         rmask = (__m128i)_mm_andnot_si128((__v2di)rmask, (__v2di)_mm_set1_epi8((char)0x80));
      |         ^~~~~
ctd.c: In function ‘prefix_op1_op2_lookup’:
ctd.c:1006:32: warning: implicit declaration of function ‘_mm256_andnot_si256’; did you mean ‘_mm256_and_si256’? [-Wimplicit-function-declaration]
 1006 |     __m256i op1_l4b = (__m256i)_mm256_andnot_si256((__v4di)mask, (__v4di)query);
      |                                ^~~~~~~~~~~~~~~~~~~
      |                                _mm256_and_si256
ctd.c:1006:5: error: can’t convert a value of type ‘int’ to vector type ‘__vector(4) long long int’ which has different size
 1006 |     __m256i op1_l4b = (__m256i)_mm256_andnot_si256((__v4di)mask, (__v4di)query);
      |     ^~~~~~~
ctd.c:1013:9: error: can’t convert a value of type ‘int’ to vector type ‘__vector(4) long long int’ which has different size
 1013 |         rmask = (__m256i)_mm256_andnot_si256(rmask, _mm256_set1_epi8((char)0x80));
      |         ^~~~~
ctd.c:1017:33: warning: implicit declaration of function ‘_mm256_insertf128_si256’ [-Wimplicit-function-declaration]
 1017 |         __m256i tb12 = (__m256i)_mm256_insertf128_si256((__v8si)_mm256_castsi128_si256((__v4si)tb1), (__v4si)tb2, 1);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~
ctd.c:1017:65: warning: implicit declaration of function ‘_mm256_castsi128_si256’; did you mean ‘_mm256_and_si256’? [-Wimplicit-function-declaration]
 1017 |         __m256i tb12 = (__m256i)_mm256_insertf128_si256((__v8si)_mm256_castsi128_si256((__v4si)tb1), (__v4si)tb2, 1);
      |                                                                 ^~~~~~~~~~~~~~~~~~~~~~
      |                                                                 _mm256_and_si256
ctd.c:1017:9: error: can’t convert a value of type ‘int’ to vector type ‘__vector(8) int’ which has different size
 1017 |         __m256i tb12 = (__m256i)_mm256_insertf128_si256((__v8si)_mm256_castsi128_si256((__v4si)tb1), (__v4si)tb2, 1);
      |         ^~~~~~~
make: *** [Makefile:74: ctd_test] Error 1

2. Inline asm. Somehow clang doesn't recognize the inline asm in the gcc style. We can just delete them and leave them as `?:` operator in C. It's guaranteed clang will output CMOVcc instrictions for optimization levels greater than 1.
**[Xiaonan]**How to do this convert? Could you provide a example?
__asm__("cmp %1, 0\n\t"
             "cmovne %0, %2"
             : "+rm"(new_val)
             : "rm"(pred), "rm"(old_val));

3. For formal verification in pitchfork, we need to comment the `cselect` operations in `register_select` function otherwise the symbolic engine will overflow.
[Xiaonan] Is is right to modify as below?
uint64_t ans = 0;
/*
ans = cselect64(idx, 0x0, ctx->rax, ans);
......
ans = cselect64(idx, 0xf, ctx->r15, ans);
*/
return ans;

**Comment by CXWorks** [comment]
Hi @xiaonan-INTC , thanks for time and patience.
1. Can you check if you include "#include <immintrin.h>" in the file and uses clang-11 for compilation? If both yes, could you please share with me the changed file, from the error messages it seems the type casting is the issue.
2.  For example, please check below. No, the "mfence" doesn't need to convert:
```
static inline int64_t cselect64s(uint64_t pred, int64_t old_val, int64_t new_val)
{
    // __asm__("cmp %1, 0\n\t"
    //         "cmovne %0, %2"
    //         : "+rm"(new_val)
    //         : "rm"(pred), "rm"(old_val));
    return pred?old_val:new_val;
}
```
3. Yes! It doesn't affect the calculation process, just affect the final result output.
4. It's the error caused by minisat, please follow the haybale (https://github.com/PLSysSec/haybale#1-install) page try to setup it and also try to install minisat in your system.

**Comment by xiaonan-INTC** [comment]
> Hi @xiaonan-INTC , thanks for time and patience.
> 
> 1. Can you check if you include "#include <immintrin.h>" in the file and uses clang-11 for compilation? If both yes, could you please share with me the changed file, from the error messages it seems the type casting is the issue.
> 2. For example, please check below. No, te "mfence" doesn't need to convert:
> 
> ```
> static inline int64_t cselect64s(uint64_t pred, int64_t old_val, int64_t new_val)
> {
>     // __asm__("cmp %1, 0\n\t"
>     //         "cmovne %0, %2"
>     //         : "+rm"(new_val)
>     //         : "rm"(pred), "rm"(old_val));
>     return pred?old_val:new_val;
> }
> ```
> 
> 3. Yes! It doesn't affect the calculation process, just affect the final result output.
> 4. It's the error caused by minisat, please follow the haybale (https://github.com/PLSysSec/haybale#1-install) page try to setup it and also try to install minisat in your system.

hi @CXWorks 
sorry to trouble, I add "#include <immintrin.h>" to ctd.c, and ensure clang is 11, but here still a error of _mm256_castsi128_si256() which was added to replace __builtin_ia32_si256_si():
Attach ctd.c for your reference(change file suffix to upload)

ctd.c:1020:88: error: incompatible type for argument 1 of ‘_mm256_castsi128_si256’
 1020 |         __m256i tb12 = (__m256i)_mm256_insertf128_si256((__v8si)_mm256_castsi128_si256((__v4si)tb1), (__v4si)tb2, 1);
      |                                                                                        ^~~~~~~~~~~
      |                                                                                        |
      |                                                                                        __vector(4) int
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/include/immintrin.h:51,
                 from ctd.c:49:
/usr/lib/gcc/x86_64-linux-gnu/9/include/avxintrin.h:1483:33: note: expected ‘__m128i’ {aka ‘__vector(2) long long int’} but argument is of type ‘__vector(4) int’
 1483 | _mm256_castsi128_si256 (__m128i __A)
      |                         ~~~~~~~~^~~
ctd.c:1020:102: error: incompatible type for argument 2 of ‘_mm256_insertf128_si256’
 1020 |         __m256i tb12 = (__m256i)_mm256_insertf128_si256((__v8si)_mm256_castsi128_si256((__v4si)tb1), (__v4si)tb2, 1);
      |                                                                                                      ^~~~~~~~~~~
      |                                                                                                      |
      |                                                                                                      __vector(4) int
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/include/immintrin.h:51,
                 from ctd.c:49:

[ctd.txt](https://github.com/intel/linux-sgx/files/12682041/ctd.txt)

**Comment by CXWorks** [comment]
Hi, it's really a weird issue and I can't reproduce it on my laptop. I think maybe you can try like below:
```
        __m128i tb1 = _mm_loadu_si128(table1 + i);
        __m128i tb2 = _mm_loadu_si128(table2 + i);
        __m256i tb12 = _mm256_insertf128_si256(_mm256_castsi128_si256(tb1), tb2, 1);
```
Here `tb1` and `tb2` are already `__m128i` type and according to the document: [cast](https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-8/mm256-castsi128-si256.html) and [insert](https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-8/mm256-insertf128-si256.html), all the types are matched.

**Comment by xiaonan-INTC** [comment]
> Hi @xiaonan-INTC , it's really a weird issue and I can't reproduce it on my laptop. I think maybe you can try like below:
> 
> ```
>         __m128i tb1 = _mm_loadu_si128(table1 + i);
>         __m128i tb2 = _mm_loadu_si128(table2 + i);
>         __m256i tb12 = _mm256_insertf128_si256(_mm256_castsi128_si256(tb1), tb2, 1);
> ```
> 
> Here `tb1` and `tb2` are already `__m128i` type and according to the document: [cast](https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-8/mm256-castsi128-si256.html) and [insert](https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-8/mm256-insertf128-si256.html), all the types are matched.

Thanks a lot, @CXWorks, that error disappeared!

But when I ran $sh run_op1_test.sh under ctd_tests/xed/, all result txt e.g. test_op1a.txt show "--------------------"

List my steps as below, could you help check where is wrong?
1. Download and build xed, build examples, 
set $export XED_BIN=/home/sgx/Desktop/aexnotify_all_tests/frameworks.security.confidential-computing.tee.sgx-linux-qatests/aexnotify_ctd_tests/3rdparties/xed/obj/wkit/bin (xed is in this folder)
2. Apply files under sdk/ to /home/sgx/Desktop/aexnotify_all_tests/frameworks.security.confidential-computing.tee.sgx-linux/sdk (test code of files under sdk/ were deleted from sgx-linux since they will be not released, so apply them to sgx-linux by manual)
3. $cd /home/sgx/Desktop/aexnotify_all_tests/frameworks.security.confidential-computing.tee.sgx-linux/sdk/trts
$make ctd_test
4. set $export CTD_BIN=/home/sgx/Desktop/aexnotify_all_tests/frameworks.security.confidential-computing.tee.sgx-linux/sdk/trts (ctd_test is in this folder) 
5. $cd /home/sgx/Desktop/aexnotify_all_tests/frameworks.security.confidential-computing.tee.sgx-linux-qatests/aexnotify_ctd_tests/xed
$sh run_op1_test.sh (annotate #export CTD_BIN=../ since it has been set as above)


BTW, in readme under ctd_tests/xed/
## 2. Build CTD
Run `./build_ctd.sh` at ctd folder

Can't find this script, where is it and does it cause above running error?

**Comment by CXWorks** [comment]
> > Hi @xiaonan-INTC , it's really a weird issue and I can't reproduce it on my laptop. I think maybe you can try like below:
> > ```
> >         __m128i tb1 = _mm_loadu_si128(table1 + i);
> >         __m128i tb2 = _mm_loadu_si128(table2 + i);
> >         __m256i tb12 = _mm256_insertf128_si256(_mm256_castsi128_si256(tb1), tb2, 1);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here `tb1` and `tb2` are already `__m128i` type and according to the document: [cast](https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-8/mm256-castsi128-si256.html) and [insert](https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-8/mm256-insertf128-si256.html), all the types are matched.
> 
> Thanks a lot, @CXWorks, that error disappeared!
> 
> But when I ran $sh run_op1_test.sh under ctd_tests/xed/, all result txt e.g. test_op1a.txt show "--------------------"
> 
> List my steps as below, could you help check where is wrong?
> 
> 1. Download and build xed, build examples,
>    set $export XED_BIN=/home/sgx/Desktop/aexnotify_all_tests/frameworks.security.confidential-computing.tee.sgx-linux-qatests/aexnotify_ctd_tests/3rdparties/xed/obj/wkit/bin (xed is in this folder)
> 2. Apply files under sdk/ to /home/sgx/Desktop/aexnotify_all_tests/frameworks.security.confidential-computing.tee.sgx-linux/sdk (test code of files under sdk/ were deleted from sgx-linux since they will be not released, so apply them to sgx-linux by manual)
> 3. $cd /home/sgx/Desktop/aexnotify_all_tests/frameworks.security.confidential-computing.tee.sgx-linux/sdk/trts
>    $make ctd_test
> 4. set $export CTD_BIN=/home/sgx/Desktop/aexnotify_all_tests/frameworks.security.confidential-computing.tee.sgx-linux/sdk/trts (ctd_test is in this folder)
> 5. $cd /home/sgx/Desktop/aexnotify_all_tests/frameworks.security.confidential-computing.tee.sgx-linux-qatests/aexnotify_ctd_tests/xed
>    $sh run_op1_test.sh (annotate #export CTD_BIN=../ since it has been set as above)
> 
> BTW, in readme under ctd_tests/xed/ 2. Build CTD Run `./build_ctd.sh` at ctd folder
> 
> Can't find this script, where is it and does it cause above running error?

Hi @xiaonan-INTC , sorry for my late response and glad to see you successfully launched it. I think that's expected, please wait for few hours or a day to finish the test. Since we are enumerating the combinations of x86_64 instructions, it's slow and each line of '------------' represents an opcode. For example, the 1 opcode case the opcode takes 1 byte, meaning there are 256 different opcodes, so I divided it into 16 parallel threads, each thread will enumerate 16 cases. 

For the result output, please wait and check the ".txt" file as log, the logic is:

The python script will feed the same, single instrcution to both CTD and XED and parse their stdout. It checks if the logic output is the same: 

    $ ./xed -64 -mpx -cet  -v 5 -j -de 0f55667788
    Initializing XED tables...
    Done initialing XED tables.
    #XED version: [v2022.10.11]
    0F55667788
    ANDNPS ANDNPS_XMMxud_MEMxud CET, DISP_WIDTH:8, EASZ:3, EOSZ:2, HAS_MODRM:1, LZCNT, MAP:1, MAX_BYTES:5, MEM0:ptr [RSI+0x77], MOD:1, MODE:2, MODRM_BYTE:102, MPXMODE, NEED_MEMDISP:8, NOMINAL_OPCODE:85, OUTREG:XMM4, P4, POS_DISP:3, POS_MODRM:2, POS_NOMINAL_OPCODE:1, REG:4, REG0:XMM4, RM:6, SMODE:2, SRM:5, TZCNT, USING_DEFAULT_SEGMENT0
    0		REG0/RW/XUD/EXPLICIT/NT_LOOKUP_FN/XMM_R
    1		MEM0/R/XUD/EXPLICIT/IMM_CONST/1
    YDIS: andnps xmm4, xmmword ptr [rsi+0x77]
    ICLASS:     ANDNPS
    CATEGORY:   LOGICAL_FP
    EXTENSION:  SSE
    IFORM:      ANDNPS_XMMxud_MEMxud
    ISA_SET:    SSE
    ATTRIBUTES: REQUIRES_ALIGNMENT 
    SHORT:      andnps xmm4, xmmword ptr [rsi+0x77]
    Encodable! 0F556677
    Identical re-encoding

With above input, we let xed only decode the first instruction and read it has `MEM0/R/`, which means it reads the memory and the logic expression is `[rsi+0x77]` and the ctd will output:

    RIP -> 0x887766550f
    cycles avg (100000 samples): 2549
    address: 0x7ffd9a2ce5e0 0x7e
    memory access: 1 READ (rv=1; ans=0x7e)
    registers: [RSI+0x77]
    inst_len: 4

And if the script detects CTD failed to output the correct logic operand, it will log it(it's expected to see many cases in some special opcode). At this time, we expect the CTD to at least mark them as no access to memory, so we have lines like `print(temp, passed, total, mod == 0)` after expection in line 171, `test_op1.py`. In a nutshell, the correct deocding case outputs nothing, the wrong case you are expected to see lots of lines but all the lines ends with "False", which means `mod==0`, no memory access.

**Comment by xiaonan-INTC** [comment]
> > > Hi @xiaonan-INTC , it's really a weird issue and I can't reproduce it on my laptop. I think maybe you can try like below:
> > > ```
> > >         __m128i tb1 = _mm_loadu_si128(table1 + i);
> > >         __m128i tb2 = _mm_loadu_si128(table2 + i);
> > >         __m256i tb12 = _mm256_insertf128_si256(_mm256_castsi128_si256(tb1), tb2, 1);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Here `tb1` and `tb2` are already `__m128i` type and according to the document: [cast](https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-8/mm256-castsi128-si256.html) and [insert](https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-8/mm256-insertf128-si256.html), all the types are matched.
> > 
> > 
> > Thanks a lot, @CXWorks, that error disappeared!
> > But when I ran $sh run_op1_test.sh under ctd_tests/xed/, all result txt e.g. test_op1a.txt show "--------------------"
> > List my steps as below, could you help check where is wrong?
> > 
> > 1. Download and build xed, build examples,
> >    set $export XED_BIN=/home/sgx/Desktop/aexnotify_all_tests/frameworks.security.confidential-computing.tee.sgx-linux-qatests/aexnotify_ctd_tests/3rdparties/xed/obj/wkit/bin (xed is in this folder)
> > 2. Apply files under sdk/ to /home/sgx/Desktop/aexnotify_all_tests/frameworks.security.confidential-computing.tee.sgx-linux/sdk (test code of files under sdk/ were deleted from sgx-linux since they will be not released, so apply them to sgx-linux by manual)
> > 3. $cd /home/sgx/Desktop/aexnotify_all_tests/frameworks.security.confidential-computing.tee.sgx-linux/sdk/trts
> >    $make ctd_test
> > 4. set $export CTD_BIN=/home/sgx/Desktop/aexnotify_all_tests/frameworks.security.confidential-computing.tee.sgx-linux/sdk/trts (ctd_test is in this folder)
> > 5. $cd /home/sgx/Desktop/aexnotify_all_tests/frameworks.security.confidential-computing.tee.sgx-linux-qatests/aexnotify_ctd_tests/xed
> >    $sh run_op1_test.sh (annotate #export CTD_BIN=../ since it has been set as above)
> > 
> > BTW, in readme under ctd_tests/xed/ 2. Build CTD Run `./build_ctd.sh` at ctd folder
> > Can't find this script, where is it and does it cause above running error?
> 
> Hi @xiaonan-INTC , sorry for my late response and glad to see you successfully launched it. I think that's expected, please wait for few hours or a day to finish the test. Since we are enumerating the combinations of x86_64 instructions, it's slow and each line of '------------' represents an opcode. For example, the 1 opcode case the opcode takes 1 byte, meaning there are 256 different opcodes, so I divided it into 16 parallel threads, each thread will enumerate 16 cases.
> 
> For the result output, please wait and check the ".txt" file as log, the logic is:
> 
> The python script will feed the same, single instrcution to both CTD and XED and parse their stdout. It checks if the logic output is the same:
> 
> ```
> $ ./xed -64 -mpx -cet  -v 5 -j -de 0f55667788
> Initializing XED tables...
> Done initialing XED tables.
> #XED version: [v2022.10.11]
> 0F55667788
> ANDNPS ANDNPS_XMMxud_MEMxud CET, DISP_WIDTH:8, EASZ:3, EOSZ:2, HAS_MODRM:1, LZCNT, MAP:1, MAX_BYTES:5, MEM0:ptr [RSI+0x77], MOD:1, MODE:2, MODRM_BYTE:102, MPXMODE, NEED_MEMDISP:8, NOMINAL_OPCODE:85, OUTREG:XMM4, P4, POS_DISP:3, POS_MODRM:2, POS_NOMINAL_OPCODE:1, REG:4, REG0:XMM4, RM:6, SMODE:2, SRM:5, TZCNT, USING_DEFAULT_SEGMENT0
> 0		REG0/RW/XUD/EXPLICIT/NT_LOOKUP_FN/XMM_R
> 1		MEM0/R/XUD/EXPLICIT/IMM_CONST/1
> YDIS: andnps xmm4, xmmword ptr [rsi+0x77]
> ICLASS:     ANDNPS
> CATEGORY:   LOGICAL_FP
> EXTENSION:  SSE
> IFORM:      ANDNPS_XMMxud_MEMxud
> ISA_SET:    SSE
> ATTRIBUTES: REQUIRES_ALIGNMENT 
> SHORT:      andnps xmm4, xmmword ptr [rsi+0x77]
> Encodable! 0F556677
> Identical re-encoding
> ```
> 
> With above input, we let xed only decode the first instruction and read it has `MEM0/R/`, which means it reads the memory and the logic expression is `[rsi+0x77]` and the ctd will output:
> 
> ```
> RIP -> 0x887766550f
> cycles avg (100000 samples): 2549
> address: 0x7ffd9a2ce5e0 0x7e
> memory access: 1 READ (rv=1; ans=0x7e)
> registers: [RSI+0x77]
> inst_len: 4
> ```
> 
> And if the script detects CTD failed to output the correct logic operand, it will log it(it's expected to see many cases in some special opcode). At this time, we expect the CTD to at least mark them as no access to memory, so we have lines like `print(temp, passed, total, mod == 0)` after expection in line 171, `test_op1.py`. In a nutshell, the correct deocding case outputs nothing, the wrong case you are expected to see lots of lines but all the lines ends with "False", which means `mod==0`, no memory access.

Dear @CXWorks 

Very clear explanation! Thanks a lot!

**Comment by lzha101** [comment]
Looks we've completed the test suite integration. Can we close this PR? @scottconstable

**Comment by scottconstable** [comment]
> Looks we've completed the test suite integration. Can we close this PR? @scottconstable

Yes

**Pull request closed without merging**
