### PR TITLE
Set pthread_info_tls.m_state to SGX_PTHREAD_EXIT in pthread_thread_run()

### PR DESCRIPTION
**Pull request by volcano0dr**
Set pthread_info_tls.m_state to SGX_PTHREAD_EXIT before _pthread_thread_run () returns. Force do initial thread when do_ecall is executed, and TLS is initialized in do_init_thread ().

### CODE REVIEW

**Comment by haitaohuang** [comment]
Can you sign off in commit message?
See CONTRIBUTING.md

**Comment by volcano0dr** [comment]
Signed-off-by: Ran Duan duanran01@baidu.com

**Comment by haitaohuang** [comment]
Please " git --amend -s" the git commit msg to include the SOB line, then do a force push to your fork.

**Comment by dingelish** [comment]
> Signed-off-by: Ran Duan [duanran01@baidu.com](mailto:duanran01@baidu.com)

You can use `git commit --amend -s` and then save and exit.

**Comment by dingelish** [comment]
@haitaohuang

**Comment by haitaohuang** [comment]
After some discussion with my colleagues, we think a more efficient fix would be setting this flag in one place by moving  "_pthread_tls_store_state(SGX_PTHREAD_EXIT)" ( at https://github.com/intel/linux-sgx/pull/488/files#diff-0d79dda8e6769f0e031c1fb00ed5898dL377) out of the block to before line 383. We incorporate that fix in next release.

**Comment by volcano0dr** [comment]
Thanks @haitaohuang ! Fix in 38edba4.

**Pull request merged**
